spring:
  profiles:
    active: development
---
spring:
  profiles: development
  redis:
    host: 172.16.1.90
    port: 6379
    password: wujiechu
  datasource:
    url: jdbc:mysql://172.16.1.90:3306/dev
    username: root
    password: wujiechu
    initialize: false
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://172.16.1.91:8761/eureka/
