spring:
  profiles:
    active: development
---
spring:
  profiles: development
  application:
    name: online-store-web
zuul:
  ignored-services: '*'
  routes:
    edge-service: /api/**
    user-service: /user/**
security:
  enable-csrf: false
  oauth2:
    resource:
      userInfoUri: http://172.16.1.90:8181/uaa/user
    client:
      accessTokenUri: http://172.16.1.90:8181/uaa/oauth/token
      userAuthorizationUri: http://172.16.1.90:8181/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
  ignored: /assets/**
eureka:
  instance:
    non-secure-port: 8787
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://172.16.1.91:8761/eureka/