spring:
  profiles:
    active: test
---
spring:
  profiles: development
  redis:
    host: 172.16.1.90
    port: 6379
  jpa:
    show_sql: false
    database: MYSQL
    generate-ddl: true
  datasource:
    url: jdbc:mysql://172.16.1.90:3306/dev?userUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: wujiechu