spring:
  profiles:
    active: development
---
spring:
  profiles: development
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dev?userUnicode=true&characterEncoding=utf-8
    username: root
    password: wujiechu
    initialize: false
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8181/uaa/user
    client:
      client-id: acme
      access-token-uri: http://localhost:8787
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
