spring:
  profiles:
    active: development
---
spring:
  profiles: development
  datasource:
    url: jdbc:mysql://172.16.1.90:3306/dev?userUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: wujiechu
    platform: mysql
security:
  oauth2:
    resource:
      userInfoUri: http://172.16.1.90:8181/uaa/user
    client:
      client-id: acme
      access-token-uri: http://116.56.140.66:8787
  enable-csrf: false
  ignored: /api/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://172.16.1.91:8761/eureka/